GRANT ALL PRIVILEGES ON blockchaindb.* TO 'admin'@'%';
FLUSH PRIVILEGES;

USE blockchaindb;

CREATE TABLE IF NOT EXISTS UserTable (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CarTable (
    CarId INT AUTO_INCREMENT PRIMARY KEY,
    Brand VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Year INT NOT NULL,
    LicensePlate VARCHAR(20) UNIQUE,
    VIN VARCHAR(17) UNIQUE,
    Color VARCHAR(30),
    Mileage INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users2Cars (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    CarId INT NOT NULL,
    AssignedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES UserTable(UserId) ON DELETE CASCADE,
    FOREIGN KEY (CarId) REFERENCES CarTable(CarId) ON DELETE CASCADE,
    UNIQUE KEY unique_user_car (UserId, CarId)
);

CREATE TABLE IF NOT EXISTS CarDataCache (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CarId INT NOT NULL,
    CarData TEXT NOT NULL, 
    InsertTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DeleteTime TIMESTAMP NULL,
    FOREIGN KEY (CarId) REFERENCES CarTable(CarId) ON DELETE CASCADE
);